language: python

python:
    - 3.4

sudo: required
dist: trusty
addons:
    firefox: "45.0"

before_install:
    - firefox --version
    - make deps
    - make pythondeps
    - python -c "import setuptools; print(setuptools.__version__)"
    - pip --version

install:
    - make install

script:
    - make devdeps
    - make pythontest
    - make jstest
    - make docs
    - make testimages
    - make testdb
    - make certs
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - sleep 3
    - pushd jupyterhub
    - mkdir -p /tmp/remoteapp
    - chmod 755 `pwd`/start.sh
    - "`pwd`/start.sh &"
    - popd
    - sleep 3
    - DISPLAY=:99 python -m unittest discover -s selenium_tests -t . -v

after_success:
    - coverage run -m tornado.testing discover
    - pip install codecov
    - codecov
    - bash <(curl -s https://codecov.io/bash)
